export default function TermsOfServicePage() {
  return (
    <div className="bg-white min-h-screen py-12 px-4 sm:px-6">
      <div className="max-w-4xl mx-auto p-8 sm:p-12 font-sans text-gray-800 leading-relaxed rounded-3xl shadow-sm border border-gray-100">
        
        <div className="mb-8">
            <a href="/" className="text-sm font-bold text-emerald-600 hover:text-emerald-700 transition">← Back to Home</a>
        </div>

        <h1 className="text-4xl font-extrabold text-[#10B981] border-b-4 border-[#10B981] pb-4 mb-4">Terms of Service</h1>
        <p className="italic text-gray-500 mb-10">Last Updated: March 2, 2026</p>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-2">By accessing or using HazelNote ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.</p>
            <p className="mb-4">HazelNote is operated by free-ed ("we," "us," or "our"). These Terms apply to all users of the Service.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">2. Description of Service</h2>
            <p className="mb-2">HazelNote is an AI-powered study workspace that helps users transform study materials into notes, flashcards, quizzes, and interactive content. The Service uses artificial intelligence to process uploaded content, including:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>PDF documents</li>
                <li>Voice recordings</li>
                <li>YouTube video transcripts</li>
                <li>Text input</li>
            </ul>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">3. User Accounts</h2>
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">3.1 Account Creation</h3>
            <p className="mb-4">To use certain features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">3.2 Account Security</h3>
            <p className="mb-4">You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">3.3 Age Requirement</h3>
            <p className="mb-4">You must be at least 13 years old to use the Service. Users under 18 must have parental or guardian consent.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">4. Subscription Plans</h2>
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">4.1 Free Plan</h3>
            <p className="mb-4">The Free plan includes limited features as specified on our website, including a maximum of 3 study sets per month.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">4.2 Pro and Max Plans</h3>
            <p className="mb-4">Paid subscription plans (Pro and Max) provide additional features and increased limits. Subscription fees are billed monthly or annually as selected.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">4.3 Billing</h3>
            <p className="mb-4">Subscriptions automatically renew unless cancelled before the renewal date. We reserve the right to change pricing with 30 days' notice to subscribers.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">4.4 Cancellation and Refunds</h3>
            <p className="mb-4">You may cancel your subscription at any time. Refunds are provided within 7 days of initial purchase if requested. No refunds for partial months after the initial period.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">5. AI Content Disclaimer</h2>
            <p className="mb-2"><strong>IMPORTANT:</strong> Content generated by HazelNote's AI may be inaccurate, incomplete, biased, or inappropriate. Users must:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Verify all AI-generated content before use in academic work</li>
                <li>Not rely solely on AI-generated content for critical decisions</li>
                <li>Understand that AI outputs are suggestions, not facts</li>
                <li>Check content against authoritative sources</li>
            </ul>
            <p className="mb-4">We make no warranties about the accuracy, reliability, or completeness of AI-generated content.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">6. User Content</h2>
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">6.1 Your Content</h3>
            <p className="mb-4">You retain ownership of content you upload to the Service. By uploading content, you grant us a license to process, store, and use that content solely to provide the Service.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">6.2 Prohibited Content</h3>
            <p className="mb-2">You may not upload content that:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Violates copyright or intellectual property rights</li>
                <li>Contains personal information of others without consent</li>
                <li>Is illegal, harmful, threatening, or offensive</li>
                <li>Contains malware or malicious code</li>
            </ul>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">6.3 Content Removal</h3>
            <p className="mb-4">We reserve the right to remove any content that violates these Terms without notice.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">7. Acceptable Use</h2>
            <p className="mb-2">You agree not to:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Use the Service for any illegal purpose</li>
                <li>Attempt to gain unauthorized access to the Service or its systems</li>
                <li>Interfere with or disrupt the Service</li>
                <li>Reverse engineer or decompile any part of the Service</li>
                <li>Use automated tools to access the Service without permission</li>
                <li>Share your account credentials with others</li>
                <li>Use the Service to violate academic integrity policies</li>
            </ul>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">8. Academic Integrity</h2>
            <p className="mb-2">HazelNote is designed as a study aid. Users are responsible for:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Following their institution's academic integrity policies</li>
                <li>Using AI-generated content appropriately</li>
                <li>Not submitting AI-generated content as their own work without proper attribution</li>
                <li>Understanding and complying with their school's AI usage policies</li>
            </ul>
            <p className="mb-4">We are not responsible for academic integrity violations resulting from misuse of the Service.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">9. Intellectual Property</h2>
            <p className="mb-2">The Service, including its design, features, and functionality, is owned by free-ed and protected by copyright, trademark, and other intellectual property laws.</p>
            <p className="mb-4">HazelNote name, logo, and branding are trademarks of free-ed. You may not use these without written permission.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">10. Third-Party Services</h2>
            <p className="mb-4">The Service may integrate with third-party services (e.g., YouTube, Google services). Your use of these services is subject to their respective terms of service.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">11. Disclaimer of Warranties</h2>
            <p className="mb-2 font-bold uppercase">THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>The Service will be uninterrupted or error-free</li>
                <li>AI-generated content will be accurate or reliable</li>
                <li>The Service will meet your specific requirements</li>
                <li>Any errors will be corrected</li>
            </ul>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">12. Limitation of Liability</h2>
            <p className="mb-2 font-bold uppercase">TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>We are not liable for any indirect, incidental, special, or consequential damages</li>
                <li>Our total liability to you shall not exceed the amount you paid us in the 12 months prior to the event giving rise to liability</li>
                <li>We are not liable for academic consequences resulting from use of AI-generated content</li>
                <li>We are not liable for content uploaded by users</li>
            </ul>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">13. Indemnification</h2>
            <p className="mb-2">You agree to indemnify and hold harmless free-ed, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:</p>
            <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Your use of the Service</li>
                <li>Your violation of these Terms</li>
                <li>Your violation of any third-party rights</li>
                <li>Content you upload to the Service</li>
            </ul>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">14. Data Privacy</h2>
            <p className="mb-4">Our Privacy Policy, available at <a href="/privacy-policy" className="text-emerald-600 underline">https://hazelnote.free-ed.site/privacy-policy</a>, explains how we collect, use, and protect your personal information. By using the Service, you consent to our Privacy Policy.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">15. Changes to Terms</h2>
            <p className="mb-4">We may modify these Terms at any time. We will notify users of material changes via email or through the Service. Continued use after changes constitutes acceptance of the new Terms.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">16. Termination</h2>
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">16.1 Termination by You</h3>
            <p className="mb-4">You may terminate your account at any time through account settings or by contacting support.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">16.2 Termination by Us</h3>
            <p className="mb-4">We may suspend or terminate your account if you violate these Terms, without refund of any fees paid.</p>
            
            <h3 className="text-lg font-bold text-[#047857] mt-6 mb-2">16.3 Effect of Termination</h3>
            <p className="mb-4">Upon termination, your right to use the Service ends immediately. We may delete your account data, though some data may be retained as required by law.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">17. Governing Law</h2>
            <p className="mb-4">These Terms are governed by the laws of the Islamic Republic of Pakistan, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Pakistan, with jurisdiction in Islamabad.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">18. Dispute Resolution</h2>
            <p className="mb-4">Any disputes arising from these Terms or the Service should first be addressed through our support team at <a href="mailto:hazelnote@free-ed.site" className="text-emerald-600 underline">hazelnote@free-ed.site</a>.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">19. Severability</h2>
            <p className="mb-4">If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.</p>
        </div>

        <div className="mb-8">
            <h2 className="text-2xl font-bold text-[#059669] mt-8 mb-4">20. Contact Information</h2>
            <p className="mb-2">For questions about these Terms, please contact us at:</p>
            <p className="mb-4">
                <strong>Email:</strong> <a href="mailto:hazelnote@free-ed.site" className="text-emerald-600 underline">hazelnote@free-ed.site</a><br/>
                <strong>Website:</strong> <a href="https://hazelnote.free-ed.site" className="text-emerald-600 underline">https://hazelnote.free-ed.site</a>
            </p>
        </div>
      </div>
    </div>
  );
}