export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0F172A] py-12 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-[#10B981] border-b-4 border-[#10B981] pb-4 mb-8">Terms of Service</h1>
        <p className="text-gray-400 italic mb-8">Last Updated: March 2, 2026</p>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">1. Acceptance of Terms</h2>
          <p className="text-gray-300 mb-4">
            By accessing or using HazelNote (&quot;the Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
          </p>
          <p className="text-gray-300">HazelNote is operated by free-ed (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). These Terms apply to all users of the Service.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">2. Description of Service</h2>
          <p className="text-gray-300 mb-4">HazelNote is an AI-powered study workspace that helps users transform study materials into notes, flashcards, quizzes, and interactive content. The Service uses artificial intelligence to process uploaded content, including:</p>
          <ul className="list-disc pl-6 text-gray-300 space-y-2">
            <li>PDF documents</li>
            <li>Voice recordings</li>
            <li>YouTube video transcripts</li>
            <li>Text input</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">3. User Accounts</h2>
          <h3 className="text-lg font-semibold text-[#34D399] mb-2">3.1 Account Creation</h3>
          <p className="text-gray-300 mb-4">To use certain features of the Service, you must create an account. You agree to provide accurate, current, and complete information during registration.</p>

          <h3 className="text-lg font-semibold text-[#34D399] mb-2">3.2 Account Security</h3>
          <p className="text-gray-300 mb-4">You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.</p>

          <h3 className="text-lg font-semibold text-[#34D399] mb-2">3.3 Age Requirement</h3>
          <p className="text-gray-300">You must be at least 13 years old to use the Service. Users under 18 must have parental or guardian consent.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">4. Subscription Plans</h2>
          <h3 className="text-lg font-semibold text-[#34D399] mb-2">4.1 Free Plan</h3>
          <p className="text-gray-300 mb-4">The Free plan includes limited features as specified on our website, including a maximum of 1 study set per month.</p>

          <h3 className="text-lg font-semibold text-[#34D399] mb-2">4.2 Pro Plan</h3>
          <p className="text-gray-300 mb-4">Paid subscription plans provide additional features and increased limits. Subscription fees are billed monthly or annually as selected.</p>

          <h3 className="text-lg font-semibold text-[#34D399] mb-2">4.3 Cancellation and Refunds</h3>
          <p className="text-gray-300">You may cancel your subscription at any time. Refunds are provided within 7 days of initial purchase if requested.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">5. AI Content Disclaimer</h2>
          <p className="text-gray-300 mb-4"><strong className="text-white">IMPORTANT:</strong> Content generated by HazelNote&apos;s AI may be inaccurate, incomplete, biased, or inappropriate. Users must:</p>
          <ul className="list-disc pl-6 text-gray-300 space-y-2">
            <li>Verify all AI-generated content before use in academic work</li>
            <li>Not rely solely on AI-generated content for critical decisions</li>
            <li>Understand that AI outputs are suggestions, not facts</li>
            <li>Check content against authoritative sources</li>
          </ul>
          <p className="text-gray-300 mt-4">We make no warranties about the accuracy, reliability, or completeness of AI-generated content.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">6. User Content</h2>
          <p className="text-gray-300 mb-4">You retain ownership of content you upload to the Service. By uploading content, you grant us a license to process, store, and use that content solely to provide the Service.</p>
          <p className="text-gray-300">You may not upload content that:</p>
          <ul className="list-disc pl-6 text-gray-300 space-y-2">
            <li>Violates copyright or intellectual property rights</li>
            <li>Contains personal information of others without consent</li>
            <li>Is illegal, harmful, threatening, or offensive</li>
            <li>Contains malware or malicious code</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">7. Academic Integrity</h2>
          <p className="text-gray-300 mb-4">HazelNote is designed as a study aid. Users are responsible for:</p>
          <ul className="list-disc pl-6 text-gray-300 space-y-2">
            <li>Following their institution&apos;s academic integrity policies</li>
            <li>Using AI-generated content appropriately</li>
            <li>Not submitting AI-generated content as their own work without proper attribution</li>
            <li>Understanding and complying with their school&apos;s AI usage policies</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">8. Limitation of Liability</h2>
          <p className="text-gray-300 mb-4">TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
          <ul className="list-disc pl-6 text-gray-300 space-y-2">
            <li>We are not liable for any indirect, incidental, special, or consequential damages</li>
            <li>Our total liability to you shall not exceed the amount you paid us in the 12 months prior to the event giving rise to liability</li>
            <li>We are not liable for academic consequences resulting from use of AI-generated content</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-bold text-[#10B981] mb-4">9. Contact Information</h2>
          <p className="text-gray-300">
            For questions about these Terms, please contact us at:<br />
            <strong className="text-white">Email:</strong> hazelnote@free-ed.site
          </p>
        </section>
      </div>
    </div>
  );
}
